global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: 'mysqld_exporter'
    static_configs:
      - targets: ['192.168.25.200:9104']
  - job_name: 'quarkus'
    scrape_interval: 2s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.25.3:8081']
