version: "3.7"
volumes:
  grafana-storage:
  prometheus:
services:
  db:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: banco_cotacao
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./api/bd/data:/var/lib/mysql
    ports:
      - 3306:3306
  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    ports:
      - 9104:9104
    volumes:
      - ./mysql-exporter/.my.cnf:/root/.my.cnf
    environment:
      - DATA_SOURCE_NAME=root:root@(db:3306)/banco_cotacao
      - collect.info_schema.tablestats=true
      - collect.info_schema.userstats=true
      - collect.info_schema.query_response_time=true
      - collect.auto_increment.columns=true
      - collect.binlog_size=true
      - collect.perf_schema.eventsstatements=true
      - collect.perf_schema.eventswaits=true
      - collect.perf_schema.file_events=true
      - collect.perf_schema.indexiowaits=true
      - collect.perf_schema.tableiowaits=true
      - collect.perf_schema.tablelocks=true
    depends_on:
      - db
  jaeger:
    image: jaegertracing/all-in-one
    container_name: container-jaeger
    ports:
      - "14269"
      - "14268:14268"
      - "14267"
      - "14250"
      - "9411:9411"
      - "16686:16686"
      - "16687"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - LOG_LEVEL=debug
    restart: on-failure
  prometheus:
    image: prom/prometheus
    command: ["--config.file=/prometheus-data/prometheus.yaml"]
    volumes:
      - ./prometheus-data:/prometheus-data
      - prometheus:/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus